# Generated by Django 4.1.9 on 2023-07-02 17:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bio", "0002_socialplatform_socialuser_delete_socialmedia"),
    ]

    operations = [
        migrations.AlterField(
            model_name="socialplatform",
            name="baseUrl",
            field=models.URLField(blank=True, null=True),
        ),
    ]
