# Generated by Django 4.1.9 on 2023-07-02 18:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bio", "0003_alter_socialplatform_baseurl"),
    ]

    operations = [
        migrations.AddField(
            model_name="socialplatform",
            name="isCopy",
            field=models.BooleanField(default=False),
        ),
    ]
