# Generated by Django 4.1.9 on 2023-07-03 00:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("bio", "0005_user_songlink"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="showCard",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="showSnowFlakes",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="UniqueLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(blank=True, null=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
