# Generated by Django 4.1.9 on 2023-07-03 00:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bio", "0006_user_showcard_user_showsnowflakes_uniquelink"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="showViewCount",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="visit_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
