# Generated by Django 4.1.7 on 2023-07-06 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0007_user_showviewcount_user_visit_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='background_image',
            new_name='backgroundImage',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='visit_count',
            new_name='views',
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='displayName',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='pfp_image',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
