# Generated by Django 4.1.7 on 2023-07-06 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0008_rename_background_image_user_backgroundimage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='pfp_image',
            new_name='pfpImage',
        ),
    ]
